### ISSUE TITLE
Support relationships

### ISSUE THREAD

**Issue by zkwentz** [rmmpaderes/ember-indexeddb-adapter#4]
How do we load `belongsTo` and `hasMany` relationships?

**Comment by rmmpaderes** [comment]
It's similar to the guide in [emberjs.com] (http://guides.emberjs.com/v2.0.0/models/defining-models/#toc_defining-relationships). You don't have to do any special configuration in the adapter to make it work.

If you have:

```js
//app/model/post.js
import DS from 'ember-data';

export default DS.Model.extend({
  title: DS.attr('string'),
  comments: DS.hasMany('comment', {async: true})
});

//app/model/comment.js
import DS from 'ember-data';

export default DS.Model.extend({
  message: DS.attr('string'),
  post: DS.belongsTo('post', {async: true})
});
```
You can get the post where comment belongs to by:
```js
let comment = this.store.findRecord('comment', <id>);

comment.get('post').then(post => {
  console.log(post.get('title'));
});
```

For getting the comments of a post however is different. Here's how:

```js
let post = this.store.findRecord('post', <id>).then(post => {
  let comments = this.store.query('comment', {post: post.get('id')});
});

**Comment by zkwentz** [comment]
It doesn't appear to store relation ids though. How does it recover the
association?

**Comment by zkwentz** [comment]
It does, just not the way I expected, instead of:

```
project_id: "1utyi"
```

it stores:

```
project: "1utyi"
```

What I ended up needing to do was add `async: true`.

**Comment by zkwentz** [comment]
Okay, after more research, that didn't resolve the issue.

Here's the issue as best I can describe it. When a parent object, say a `post` hasMany of another model, say `comments`, nothing in the adapter says to get those related records.

And because the hasMany is stored on the records that belongTo the parent, there is no reference to those children when you get the parent.

Seems what needs to happen is when you find a record, you need to look at `eachRelationship`, and if they are a `hasMany`, make a subsequent query for those child records with the parent's id.

Does that make sense?

**Comment by rmmpaderes** [comment]
If I understand it correctly, comments are not getting saved in post's hasMany relationship. This is expected as it's also done by design in Ember. Typically it's best practice to store the relationship in the belongsTo record rather than both in the belongsTo and hasMany records. Now I may override that Ember design but that's not the route I'm taking. :)

You can however, overcome this by using DS.EmbeddedRecordsMixin. I've never tried it myself though, but [here's](http://emberjs.com/api/data/classes/DS.EmbeddedRecordsMixin.html) the emberjs guide to it. To add, I think what you're looking for specifically should be [here](http://emberjs.com/api/data/classes/DS.EmbeddedRecordsMixin.html#method_serializeHasMany).
